import type { PillarsIllustrationProps } from './components/PillarsIllustration';

export const foundationPillarsProps = {
  auxiliaryIconFillColor: '#212121',
  beamColor: '#449c40',
  beamEmissionRandomness: 100,
  beamEnabled: true,
  beamHeadGlowBlur: 10,
  beamHeadGlowOpacity: 0.6,
  beamHeadGlowRadius: 18,
  beamHighlightColor: '#c9ebc7',
  beamSpeed: 1.4,
  beamTrailLength: 32,
  burstFadeTime: 1700,
  burstRadius: 19,
  burstStrength: 0.5,
  maxConcurrentBeams: 10,
  numberOfNodesTop: 4,
  numberOfNodesBottom: 5,
  auxiliaryNodeSpacing: 0.6,
  color: '#f3f5ef',
  centralIconFillColor: '#1d281d',
  centralIconFillMode: 'black',
  centralIconStrokeOpacity: 0.52,
  connectorColor: '#ffffff',
  connectorOpacity: 0.22,
  connectorRadius: 10,
  connectorWidth: 1.25,
  showContinuationConnectors: true,
  gradientStartColor: '#066b43',
  gradientMidColor: '#03492b',
  gradientEndColor: '#052f24',
  gridColor: '#39473f',
  gridDensity: 30,
  gridOpacity: 0,
  width: '20rem',
  height: '45rem',
  iconSize: 40,
  strokeWidth: 1.5,
} satisfies PillarsIllustrationProps;
