import type { SignalFlowIllustrationProps } from './types';

export const heroSignalFlowProps = {
  mode: 'dark',
  showInterface: false,
  gridOpacity: 1,
  gridDensity: 30,
  connectorOpacity: 0.62,
  connectorStroke: 'dashed',
  connectorWidth: 1.25,
  pathCurve: 86,
  outlineOpacity: 0.25,
  outlineWidth: 1,
  nodeDepth: 18,
  nodeCornerRadius: 14,
  perspectiveEffect: 82,
  cameraPitch: 45,
  cameraYaw: 15,
  cameraZoom: 0.8,
  scrollTilt: 45,
  scrollZoom: 1.2,
  scrollRange: 700,
  minDelay: 500,
  maxDelay: 1800,
  progressBarHeight: 8,
  concurrentBeams: 10,
  minEmitDelay: 500,
  maxEmitDelay: 1400,
} satisfies SignalFlowIllustrationProps;
