import {
  businessFlowHeroTreatments,
  businessFlowPalettes,
} from '@/features/business-flow-palette';
import type { BusinessFlowHorizontalProps } from './components/BusinessFlowHorizontal';

export const businessFlowHorizontalHomepageDarkProps = {
  activityStrategy: 'visible',
  auxiliaryIconFillColor: businessFlowHeroTreatments.dark.iconFill,
  auxiliaryIconOpacity: 0.72,
  beamColor: businessFlowPalettes.dark.beam,
  beamEmissionRandomness: 100,
  beamEnabled: true,
  beamGlowIntensity: 1,
  beamHeadGlowBlur: 2,
  beamHeadGlowOpacity: 1,
  beamHeadGlowRadius: 11,
  beamHighlightColor: businessFlowPalettes.dark.beamHighlight,
  beamSpeed: 1.4,
  beamTrailLength: 135,
  beamWidth: 1.75,
  burstFadeTime: 900,
  burstRadius: 24,
  burstStrength: 0.5,
  centralIconFillColor: businessFlowHeroTreatments.dark.iconFill,
  centralIconOpacity: 1,
  centralIconStrokeOpacity: 1,
  connectorColor: businessFlowHeroTreatments.dark.connectorColor,
  connectorOpacity: 0.62,
  connectorWidth: 1.25,
  gridColor: businessFlowPalettes.dark.grid,
  gridDensity: 30,
  gridOpacity: 0,
  height: '50rem',
  iconSize: 44,
  iconStrokeColor: businessFlowHeroTreatments.dark.iconStroke,
  loadStrategy: 'near-viewport',
  maxConcurrentBeams: 5,
  numberOfNodesLeft: 8,
  numberOfNodesRight: 8,
  nodeBodyColor: businessFlowPalettes.dark.nodeBody,
  nodeFrontGradientAngle: 117,
  nodeFrontGradientEndColor: businessFlowHeroTreatments.dark.frontGradient.end,
  nodeFrontGradientMidColor: businessFlowHeroTreatments.dark.frontGradient.mid,
  nodeFrontGradientStartColor: businessFlowHeroTreatments.dark.frontGradient.start,
  nodeShadowBias: -0.0003,
  nodeShadowBlurSamples: 16,
  nodeShadowColor: businessFlowPalettes.dark.nodeShadow,
  nodeShadowLightX: -6,
  nodeShadowLightY: 14,
  nodeShadowLightZ: -5,
  nodeShadowNormalBias: 0.025,
  nodeShadowOpacity: 0.5,
  nodeShadowRadius: 8,
  nodeProgressMaxDelay: 1800,
  nodeProgressMinDelay: 500,
  nodeProgressMode: 'outline',
  nodeProgressSize: 15,
  nodeSideXGradientAngle: 360,
  nodeSideXGradientEndColor: businessFlowHeroTreatments.dark.sideXGradient.end,
  nodeSideXGradientMidColor: businessFlowHeroTreatments.dark.sideXGradient.mid,
  nodeSideXGradientStartColor: businessFlowHeroTreatments.dark.sideXGradient.start,
  nodeSideZGradientAngle: 177,
  nodeSideZGradientEndColor: businessFlowHeroTreatments.dark.sideZGradient.end,
  nodeSideZGradientMidColor: businessFlowHeroTreatments.dark.sideZGradient.mid,
  nodeSideZGradientStartColor: businessFlowHeroTreatments.dark.sideZGradient.start,
  outlineOpacity: 0,
  outlineWidth: 1,
  preloadMargin: '600px 0px',
  resolutionScale: 'display',
  strokeWidth: 2.25,
  width: 'min(28.8rem, 100%)',
} satisfies BusinessFlowHorizontalProps;

export const businessFlowHorizontalHomepageLightProps = {
  activityStrategy: 'visible',
  auxiliaryIconFillColor: businessFlowPalettes.light.white,
  auxiliaryIconOpacity: 0.72,
  beamColor: businessFlowPalettes.light.beam,
  beamEmissionRandomness: 100,
  beamEnabled: true,
  beamGlowIntensity: 1,
  beamHeadGlowBlur: 32,
  beamHeadGlowOpacity: 0.6,
  beamHeadGlowRadius: 11,
  beamHighlightColor: businessFlowPalettes.light.white,
  beamSpeed: 1.4,
  beamTrailLength: 49,
  beamWidth: 2.1,
  burstFadeTime: 900,
  burstRadius: 24,
  burstStrength: 0.5,
  centralIconFillColor: businessFlowPalettes.light.white,
  centralIconOpacity: 1,
  centralIconStrokeOpacity: 1,
  connectorColor: businessFlowPalettes.light.beam,
  connectorOpacity: 1,
  connectorWidth: 1.5,
  gridColor: businessFlowPalettes.light.grid,
  gridDensity: 30,
  gridOpacity: 0,
  height: '50rem',
  iconSize: 40,
  iconStrokeColor: businessFlowPalettes.light.beam,
  loadStrategy: 'near-viewport',
  maxConcurrentBeams: 5,
  numberOfNodesLeft: 8,
  numberOfNodesRight: 8,
  nodeBodyColor: businessFlowPalettes.light.nodeBody,
  nodeFrontGradientAngle: 117,
  nodeFrontGradientEndColor: businessFlowPalettes.light.homepageNodeFrontStart,
  nodeFrontGradientMidColor: businessFlowPalettes.light.white,
  nodeFrontGradientStartColor: businessFlowPalettes.light.white,
  nodeShadowBias: 0,
  nodeShadowBlurSamples: 20,
  nodeShadowColor: businessFlowPalettes.light.nodeShadow,
  nodeShadowLightX: 2,
  nodeShadowLightY: 9,
  nodeShadowLightZ: -2.5,
  nodeShadowNormalBias: 0.025,
  nodeShadowOpacity: 0.15,
  nodeShadowRadius: 4,
  nodeProgressMaxDelay: 1800,
  nodeProgressMinDelay: 500,
  nodeProgressMode: 'outline',
  nodeProgressSize: 15,
  nodeSideXGradientAngle: 360,
  nodeSideXGradientEndColor: businessFlowHeroTreatments.light.sideXGradient.end,
  nodeSideXGradientMidColor: businessFlowHeroTreatments.light.sideXGradient.mid,
  nodeSideXGradientStartColor: businessFlowHeroTreatments.light.sideXGradient.start,
  nodeSideZGradientAngle: 177,
  nodeSideZGradientEndColor: businessFlowHeroTreatments.light.sideZGradient.end,
  nodeSideZGradientMidColor: businessFlowHeroTreatments.light.sideZGradient.mid,
  nodeSideZGradientStartColor: businessFlowHeroTreatments.light.sideZGradient.start,
  outlineOpacity: 0.25,
  outlineWidth: 1.25,
  preloadMargin: '600px 0px',
  resolutionScale: 'display',
  strokeWidth: 3,
  width: 'min(28.8rem, 100%)',
} satisfies BusinessFlowHorizontalProps;
