import {
  businessFlowHeroTreatments,
  businessFlowPalettes,
} from '@/features/business-flow-palette';
import type { BusinessFlowHorizontalProps } from './components/BusinessFlowHorizontal';

export const businessFlowHorizontalHomepageDarkProps = {
  activityStrategy: 'visible',
  auxiliaryIconFillColor: businessFlowHeroTreatments.dark.iconFill,
  beamColor: businessFlowPalettes.dark.beam,
  beamEmissionRandomness: 100,
  beamEnabled: true,
  beamHeadGlowBlur: 2,
  beamHeadGlowOpacity: 1,
  beamHeadGlowRadius: 11,
  beamHighlightColor: businessFlowPalettes.dark.beamHighlight,
  beamSpeed: 1.4,
  beamTrailLength: 135,
  burstFadeTime: 900,
  burstRadius: 24,
  burstStrength: 0.5,
  centralIconFillColor: businessFlowHeroTreatments.dark.iconFill,
  centralIconStrokeOpacity: 1,
  connectorColor: businessFlowHeroTreatments.dark.connectorColor,
  connectorOpacity: 0.62,
  connectorWidth: 1.25,
  gridColor: businessFlowPalettes.dark.grid,
  gridDensity: 30,
  gridOpacity: 0,
  height: '50rem',
  iconSize: 44,
  iconStrokeColor: businessFlowHeroTreatments.dark.iconStroke,
  loadStrategy: 'near-viewport',
  maxConcurrentBeams: 5,
  numberOfNodesLeft: 8,
  numberOfNodesRight: 8,
  nodeShadowBias: -0.0003,
  nodeShadowBlurSamples: 16,
  nodeShadowColor: businessFlowPalettes.dark.nodeShadow,
  nodeShadowLightX: -6,
  nodeShadowLightY: 14,
  nodeShadowLightZ: -5,
  nodeShadowNormalBias: 0.025,
  nodeShadowOpacity: 0.5,
  nodeShadowRadius: 8,
  nodeProgressMaxDelay: 1800,
  nodeProgressMinDelay: 500,
  nodeProgressMode: 'outline',
  nodeProgressSize: 15,
  outlineOpacity: 0,
  outlineWidth: 1,
  preloadMargin: '600px 0px',
  resolutionScale: 'display',
  strokeWidth: 2.25,
  width: 'min(28.8rem, 100%)',
} satisfies BusinessFlowHorizontalProps;

export const businessFlowHorizontalHomepageLightProps = {
  activityStrategy: 'visible',
  auxiliaryIconFillColor: businessFlowHeroTreatments.light.iconFill,
  beamColor: businessFlowPalettes.light.beam,
  beamEmissionRandomness: 100,
  beamEnabled: true,
  beamHeadGlowBlur: 2,
  beamHeadGlowOpacity: 1,
  beamHeadGlowRadius: 11,
  beamHighlightColor: businessFlowPalettes.light.beamHighlight,
  beamSpeed: 1.4,
  beamTrailLength: 135,
  burstFadeTime: 900,
  burstRadius: 24,
  burstStrength: 0.5,
  centralIconFillColor: businessFlowHeroTreatments.light.iconFill,
  centralIconStrokeOpacity: 1,
  connectorColor: businessFlowHeroTreatments.light.connectorColor,
  connectorOpacity: 0.62,
  connectorWidth: 1.25,
  gridColor: businessFlowPalettes.light.grid,
  gridDensity: 30,
  gridOpacity: 0,
  height: '50rem',
  iconSize: 44,
  iconStrokeColor: businessFlowHeroTreatments.light.iconStroke,
  loadStrategy: 'near-viewport',
  maxConcurrentBeams: 5,
  numberOfNodesLeft: 8,
  numberOfNodesRight: 8,
  nodeShadowBias: -0.0003,
  nodeShadowBlurSamples: 16,
  nodeShadowColor: businessFlowPalettes.light.nodeShadow,
  nodeShadowLightX: -6,
  nodeShadowLightY: 14,
  nodeShadowLightZ: -5,
  nodeShadowNormalBias: 0.025,
  nodeShadowOpacity: 0.38,
  nodeShadowRadius: 8,
  nodeProgressMaxDelay: 1800,
  nodeProgressMinDelay: 500,
  nodeProgressMode: 'outline',
  nodeProgressSize: 15,
  outlineOpacity: 0.3,
  outlineWidth: 1.25,
  preloadMargin: '600px 0px',
  resolutionScale: 'display',
  strokeWidth: 2.25,
  width: 'min(28.8rem, 100%)',
} satisfies BusinessFlowHorizontalProps;
