import type { BusinessFlowHorizontalProps } from './components/BusinessFlowHorizontal';

export const businessFlowHorizontalHomepageProps = {
  activityStrategy: 'visible',
  beamEmissionRandomness: 100,
  beamEnabled: true,
  beamHeadGlowBlur: 2,
  beamHeadGlowOpacity: 1,
  beamHeadGlowRadius: 11,
  beamSpeed: 1.4,
  beamTrailLength: 135,
  burstFadeTime: 900,
  burstRadius: 24,
  burstStrength: 0.5,
  centralIconStrokeOpacity: 1,
  connectorOpacity: 0.8,
  connectorWidth: 1,
  gridDensity: 30,
  gridOpacity: 0,
  height: '50rem',
  iconSize: 44,
  loadStrategy: 'near-viewport',
  maxConcurrentBeams: 5,
  numberOfNodesLeft: 8,
  numberOfNodesRight: 8,
  nodeProgressMaxDelay: 1800,
  nodeProgressMinDelay: 500,
  nodeProgressMode: 'outline',
  nodeProgressSize: 15,
  preloadMargin: '600px 0px',
  resolutionScale: 'display',
  strokeWidth: 2.25,
  width: 'min(28.8rem, 100%)',
} satisfies BusinessFlowHorizontalProps;
