import type { FlowConfig, FlowNodeConfig } from './types';

const nodes = [
  { id: 'core', position: [0, -5], label: 'CORE', svg: 'hexagon_default.svg', size: [4.3, 2.2], tier: 0, shape: 'hexagon' },
  { id: 'vault', position: [0, -0.7], label: 'VAULT', svg: 'triangle_default.svg', size: [3.2, 1.8], tier: 1, shape: 'triangle' },
  { id: 'library', position: [6.6, -0.7], label: 'LIBRARY', svg: 'square_default.svg', size: [3.2, 1.8], tier: 1, shape: 'square' },
  { id: 'metrics', position: [0, 3.2], label: 'METRICS', svg: 'hexagon_default.svg', size: [2.6, 1.5], tier: 2, shape: 'hexagon' },
  { id: 'stack', position: [3.3, 3.2], label: 'STACK', svg: 'triangle_default.svg', size: [2.6, 1.5], tier: 2, shape: 'triangle' },
  { id: 'secure', position: [9.9, 3.2], label: 'SECURE', svg: 'triangle_default.svg', size: [2.6, 1.5], tier: 2, shape: 'triangle' },
  { id: 'records', position: [0, 7.4], label: 'RECORDS', svg: 'square_default.svg', size: [2.15, 1.25], tier: 3, shape: 'square' },
  { id: 'graph', position: [3.3, 7.4], label: 'GRAPH', svg: 'triangle_default.svg', size: [2.15, 1.25], tier: 3, shape: 'triangle' },
  { id: 'profile', position: [6.6, 7.4], label: 'PROFILE', svg: 'square_default.svg', size: [2.15, 1.25], tier: 3, shape: 'square' },
  { id: 'labels', position: [13.2, 7.4], label: 'LABELS', svg: 'circle_default.svg', size: [2.15, 1.25], tier: 3, shape: 'circle' },
  { id: 'pipeline', position: [3.3, 11], label: 'PIPELINE', svg: 'square_default.svg', size: [2.15, 1.25], tier: 4, shape: 'square' },
  { id: 'policy', position: [6.6, 11], label: 'POLICY', svg: 'rectangle_default.svg', size: [2.15, 1.25], tier: 4, shape: 'rectangle' },
  { id: 'schedule', position: [13.2, 11], label: 'SCHEDULE', svg: 'hexagon_default.svg', size: [2.15, 1.25], tier: 4, shape: 'hexagon' },
  { id: 'build', position: [0, 15.2], label: 'BUILD', svg: 'rectangle_default.svg', size: [2.15, 1.25], tier: 5, shape: 'rectangle' },
  { id: 'release', position: [3.3, 15.2], label: 'RELEASE', svg: 'hexagon_default.svg', size: [2.15, 1.25], tier: 5, shape: 'hexagon' },
  { id: 'access', position: [6.6, 15.2], label: 'ACCESS', svg: 'circle_default.svg', size: [2.15, 1.25], tier: 5, shape: 'circle' },
  { id: 'events', position: [13.2, 15.2], label: 'EVENTS', svg: 'rectangle_default.svg', size: [2.15, 1.25], tier: 5, shape: 'rectangle' },
  { id: 'deploy', position: [0, 19], label: 'DEPLOY', svg: 'circle_default.svg', size: [2.15, 1.25], tier: 6, shape: 'circle' },
  { id: 'identity', position: [3.3, 19], label: 'IDENTITY', svg: 'hexagon_default.svg', size: [2.15, 1.25], tier: 6, shape: 'hexagon' },
  { id: 'signals', position: [9.9, 19], label: 'SIGNALS', svg: 'rectangle_default.svg', size: [2.15, 1.25], tier: 6, shape: 'rectangle' },
  { id: 'routes', position: [13.2, 19], label: 'ROUTES', svg: 'hexagon_default.svg', size: [2.15, 1.25], tier: 6, shape: 'hexagon' },
  { id: 'publish', position: [0, 23.4], label: 'PUBLISH', svg: 'rectangle_default.svg', size: [2.15, 1.25], tier: 7, shape: 'rectangle' },
  { id: 'govern', position: [6.6, 23.4], label: 'GOVERN', svg: 'circle_default.svg', size: [2.15, 1.25], tier: 7, shape: 'circle' },
  { id: 'stream', position: [13.2, 23.4], label: 'STREAM', svg: 'rectangle_default.svg', size: [2.15, 1.25], tier: 7, shape: 'rectangle' },
] satisfies FlowNodeConfig[];

export const homepageFlow = {
  root: 'core',
  nodes,
  branches: {
    core: ['vault', 'library'],
    vault: ['metrics', 'stack'],
    library: ['secure'],
    metrics: ['records'],
    stack: ['graph'],
    secure: ['profile', 'labels'],
    graph: ['pipeline', 'profile'],
    profile: ['policy'],
    labels: ['schedule'],
    pipeline: ['build', 'release'],
    policy: ['access'],
    schedule: ['events'],
    build: ['deploy'],
    release: ['identity'],
    access: ['identity', 'signals'],
    events: ['routes'],
    deploy: ['publish'],
    identity: ['govern'],
    signals: ['govern'],
    routes: ['stream'],
  },
} satisfies FlowConfig;
