import type { BusinessFlow3DProps } from './types';
import { businessFlowPalette } from '../business-flow-palette';

export const businessFlow3DHomepageProps = {
  activityStrategy: 'visible',
  mode: 'dark',
  loadStrategy: 'eager',
  resolutionScale: 'display',
  showInterface: false,
  interactive: false,
  fogEnabled: true,
  gridOpacity: 0.2,
  gridDensity: 30,
  gridMaskRadius: 800,
  gridMaskBlur: 480,
  connectorOpacity: 0.62,
  connectorStroke: 'dashed',
  connectorWidth: 1.25,
  showContinuationConnectors: true,
  pathCurve: 86,
  outlineOpacity: 0,
  outlineWidth: 1,
  nodeScale: 0.7,
  nodeDepth: 20,
  nodeDepthRandom: 42,
  nodeShape: 'custom',
  nodeCornerRadius: 10,
  nodeIconOpacity: 0.5,
  nodeFrontGradientAngle: 117,
  nodeSideXGradientAngle: 360,
  nodeSideZGradientAngle: 177,
  nodeFrontGradientStartColor: businessFlowPalette.frontGradient.start,
  nodeFrontGradientMidColor: businessFlowPalette.frontGradient.mid,
  nodeFrontGradientEndColor: businessFlowPalette.frontGradient.end,
  nodeSideXGradientEndColor: businessFlowPalette.sideXGradient.end,
  nodeSideZGradientStartColor: businessFlowPalette.sideZGradient.start,
  nodeSideZGradientMidColor: businessFlowPalette.sideZGradient.mid,
  nodeSideZGradientEndColor: businessFlowPalette.sideZGradient.end,
  perspectiveEffect: 75,
  cameraPitch: 33.19,
  cameraYaw: 0.35,
  cameraZoom: 0.91,
  emitterX: 3,
  emitterY: -8,
  scrollTilt: 41.81,
  scrollRange: 700,
  minDelay: 200,
  maxDelay: 800,
  speed: 0.8,
  nodeProgressMode: 'outline',
  progressPadding: 1,
  progressBarHeight: 15,
  concurrentBeams: 10,
  minEmitDelay: 150,
  maxEmitDelay: 500,
} satisfies BusinessFlow3DProps;
