import type { BusinessFlowVerticalProps } from './components/BusinessFlowVertical';
import { businessFlowPalette } from '../business-flow-palette';

export const businessFlowVerticalHomepageProps = {
  activityStrategy: 'visible',
  auxiliaryIconFillColor: businessFlowPalette.auxiliaryIconFill,
  beamColor: businessFlowPalette.beam,
  beamEmissionRandomness: 100,
  beamEnabled: true,
  beamHeadGlowBlur: 32,
  beamHeadGlowOpacity: 0,
  beamHeadGlowRadius: 0,
  beamHighlightColor: businessFlowPalette.beamHighlight,
  beamSpeed: 1.4,
  beamTrailLength: 0,
  burstFadeTime: 1700,
  burstRadius: 25,
  burstStrength: 0.5,
  maxConcurrentBeams: 5,
  numberOfNodesTop: 4,
  numberOfNodesBottom: 5,
  auxiliaryNodeSpacing: 0.6,
  color: businessFlowPalette.iconStroke,
  centralIconFillColor: businessFlowPalette.centralIconFill,
  centralIconFillMode: 'black',
  centralIconStrokeOpacity: 0.91,
  connectorColor: businessFlowPalette.connector,
  connectorOpacity: 0.6,
  connectorRadius: 10,
  connectorWidth: 1,
  showContinuationConnectors: true,
  gradientStartColor: businessFlowPalette.frontGradient.start,
  gradientMidColor: businessFlowPalette.frontGradient.mid,
  gradientEndColor: businessFlowPalette.frontGradient.end,
  gridColor: businessFlowPalette.grid,
  gridDensity: 30,
  gridOpacity: 0,
  width: '20rem',
  height: '45rem',
  iconSize: 40,
  loadStrategy: 'near-viewport',
  nodeProgressMaxDelay: 1800,
  nodeProgressMinDelay: 500,
  nodeProgressMode: 'outline',
  nodeProgressSize: 15,
  preloadMargin: '600px 0px',
  resolutionScale: 'display',
  strokeWidth: 1.5,
} satisfies BusinessFlowVerticalProps;
