import {
  businessFlowHeroTreatments,
  businessFlowPalettes,
} from '@/features/business-flow-palette';
import type { BusinessFlowVerticalProps } from './components/BusinessFlowVertical';

export const businessFlowVerticalHomepageDarkProps = {
  activityStrategy: 'visible',
  auxiliaryIconFillColor: businessFlowHeroTreatments.dark.iconFill,
  beamColor: businessFlowPalettes.dark.beam,
  beamEmissionRandomness: 100,
  beamEnabled: true,
  beamHeadGlowBlur: 32,
  beamHeadGlowOpacity: 0,
  beamHeadGlowRadius: 0,
  beamHighlightColor: businessFlowPalettes.dark.beamHighlight,
  beamSpeed: 1.4,
  beamTrailLength: 0,
  burstFadeTime: 1700,
  burstRadius: 25,
  burstStrength: 0.5,
  maxConcurrentBeams: 5,
  numberOfNodesTop: 4,
  numberOfNodesBottom: 5,
  auxiliaryNodeSpacing: 0.6,
  centralIconFillColor: businessFlowHeroTreatments.dark.iconFill,
  centralIconFillMode: 'black',
  centralIconStrokeOpacity: 0.91,
  connectorColor: businessFlowHeroTreatments.dark.connectorColor,
  connectorOpacity: 0.62,
  connectorRadius: 10,
  connectorWidth: 1.25,
  gradientEndColor: businessFlowHeroTreatments.dark.frontGradient.end,
  gradientMidColor: businessFlowHeroTreatments.dark.frontGradient.mid,
  gradientStartColor: businessFlowHeroTreatments.dark.frontGradient.start,
  gridColor: businessFlowPalettes.dark.grid,
  showContinuationConnectors: true,
  gridDensity: 30,
  gridOpacity: 0,
  width: '20rem',
  height: '45rem',
  iconSize: 40,
  iconStrokeColor: businessFlowHeroTreatments.dark.iconStroke,
  loadStrategy: 'near-viewport',
  nodeShadowBias: -0.0003,
  nodeShadowBlurSamples: 16,
  nodeShadowColor: businessFlowPalettes.dark.nodeShadow,
  nodeShadowLightX: -6,
  nodeShadowLightY: 14,
  nodeShadowLightZ: -5,
  nodeShadowNormalBias: 0.025,
  nodeShadowOpacity: 0.5,
  nodeShadowRadius: 8,
  nodeProgressMaxDelay: 1800,
  nodeProgressMinDelay: 500,
  nodeProgressMode: 'outline',
  nodeProgressSize: 15,
  preloadMargin: '600px 0px',
  resolutionScale: 'display',
  strokeWidth: 1.5,
} satisfies BusinessFlowVerticalProps;

export const businessFlowVerticalHomepageLightProps = {
  activityStrategy: 'visible',
  auxiliaryIconFillColor: businessFlowHeroTreatments.light.iconFill,
  beamColor: businessFlowPalettes.light.beam,
  beamEmissionRandomness: 100,
  beamEnabled: true,
  beamHeadGlowBlur: 32,
  beamHeadGlowOpacity: 0,
  beamHeadGlowRadius: 0,
  beamHighlightColor: businessFlowPalettes.light.beamHighlight,
  beamSpeed: 1.4,
  beamTrailLength: 0,
  burstFadeTime: 1700,
  burstRadius: 25,
  burstStrength: 0.5,
  maxConcurrentBeams: 5,
  numberOfNodesTop: 4,
  numberOfNodesBottom: 5,
  auxiliaryNodeSpacing: 0.6,
  centralIconFillColor: businessFlowHeroTreatments.light.iconFill,
  centralIconFillMode: 'black',
  centralIconStrokeOpacity: 0.91,
  connectorColor: businessFlowHeroTreatments.light.connectorColor,
  connectorOpacity: 0.62,
  connectorRadius: 10,
  connectorWidth: 1.25,
  gradientEndColor: businessFlowHeroTreatments.light.frontGradient.end,
  gradientMidColor: businessFlowHeroTreatments.light.frontGradient.mid,
  gradientStartColor: businessFlowHeroTreatments.light.frontGradient.start,
  gridColor: businessFlowPalettes.light.grid,
  showContinuationConnectors: true,
  gridDensity: 30,
  gridOpacity: 0,
  width: '20rem',
  height: '45rem',
  iconSize: 40,
  iconStrokeColor: businessFlowHeroTreatments.light.iconStroke,
  loadStrategy: 'near-viewport',
  nodeShadowBias: -0.0003,
  nodeShadowBlurSamples: 16,
  nodeShadowColor: businessFlowPalettes.light.nodeShadow,
  nodeShadowLightX: -6,
  nodeShadowLightY: 14,
  nodeShadowLightZ: -5,
  nodeShadowNormalBias: 0.025,
  nodeShadowOpacity: 0.38,
  nodeShadowRadius: 8,
  nodeProgressMaxDelay: 1800,
  nodeProgressMinDelay: 500,
  nodeProgressMode: 'outline',
  nodeProgressSize: 15,
  preloadMargin: '600px 0px',
  resolutionScale: 'display',
  strokeWidth: 1.5,
} satisfies BusinessFlowVerticalProps;
