import type { BusinessFlowVerticalProps } from './components/BusinessFlowVertical';

export const businessFlowVerticalHomepageProps = {
  activityStrategy: 'visible',
  beamEmissionRandomness: 100,
  beamEnabled: true,
  beamHeadGlowBlur: 32,
  beamHeadGlowOpacity: 0,
  beamHeadGlowRadius: 0,
  beamSpeed: 1.4,
  beamTrailLength: 0,
  burstFadeTime: 1700,
  burstRadius: 25,
  burstStrength: 0.5,
  maxConcurrentBeams: 5,
  numberOfNodesTop: 4,
  numberOfNodesBottom: 5,
  auxiliaryNodeSpacing: 0.6,
  centralIconFillMode: 'black',
  centralIconStrokeOpacity: 0.91,
  connectorOpacity: 0.6,
  connectorRadius: 10,
  connectorWidth: 1,
  showContinuationConnectors: true,
  gridDensity: 30,
  gridOpacity: 0,
  width: '20rem',
  height: '45rem',
  iconSize: 40,
  loadStrategy: 'near-viewport',
  nodeProgressMaxDelay: 1800,
  nodeProgressMinDelay: 500,
  nodeProgressMode: 'outline',
  nodeProgressSize: 15,
  preloadMargin: '600px 0px',
  resolutionScale: 'display',
  strokeWidth: 1.5,
} satisfies BusinessFlowVerticalProps;
