import { businessFlowPalette } from '../business-flow-palette';
import type { BusinessCoreNodeFlowProps } from './components/BusinessCoreNodeFlow';

export const businessCoreNodeFlowContactProps = {
  activityStrategy: 'visible',
  auxiliaryIcon: 'mixed',
  auxiliaryIconFillColor: businessFlowPalette.horizontalAuxiliaryIconFill,
  beamColor: businessFlowPalette.beam,
  beamEmissionRandomness: 100,
  beamEnabled: true,
  beamGlowIntensity: 1,
  beamHeadGlowBlur: 2,
  beamHeadGlowOpacity: 1,
  beamHeadGlowRadius: 11,
  beamHighlightColor: businessFlowPalette.beamHighlight,
  beamSpeed: 1.4,
  beamTrailLength: 135,
  beamWidth: 1.4,
  burstFadeTime: 900,
  burstRadius: 24,
  burstStrength: 0.5,
  centralIcon: 'profile',
  centralIconFillColor: businessFlowPalette.horizontalCentralIconFill,
  centralIconStrokeOpacity: 1,
  color: businessFlowPalette.horizontalIconStroke,
  connectorColor: businessFlowPalette.connector,
  connectorOpacity: 0.8,
  connectorStroke: 'dashed',
  connectorWidth: 1,
  gridColor: businessFlowPalette.grid,
  gridDensity: 30,
  gridOpacity: 0,
  iconSize: 44,
  loadStrategy: 'near-viewport',
  maxConcurrentBeams: 6,
  nodeProgressMaxDelay: 1800,
  nodeProgressMinDelay: 500,
  nodeProgressMode: 'outline',
  nodeProgressSize: 15,
  numberOfAuxiliaryConnections: 12,
  resolutionScale: 'display',
  showAuxiliaryNodes: false,
  size: 'min(22rem, 100%)',
  strokeWidth: 0.5,
} satisfies BusinessCoreNodeFlowProps;

export const businessCoreNodeFlowWaitlistProps = {
  activityStrategy: 'visible',
  auxiliaryIcon: 'mixed',
  auxiliaryIconFillColor: businessFlowPalette.horizontalAuxiliaryIconFill,
  beamColor: businessFlowPalette.beam,
  beamEmissionRandomness: 100,
  beamEnabled: true,
  beamGlowIntensity: 1,
  beamHeadGlowBlur: 2,
  beamHeadGlowOpacity: 1,
  beamHeadGlowRadius: 11,
  beamHighlightColor: businessFlowPalette.beamHighlight,
  beamSpeed: 1.4,
  beamTrailLength: 135,
  beamWidth: 1.4,
  burstFadeTime: 900,
  burstRadius: 24,
  burstStrength: 0.5,
  centralIcon: 'profile',
  centralIconFillColor: businessFlowPalette.horizontalCentralIconFill,
  centralIconStrokeOpacity: 1,
  color: businessFlowPalette.horizontalIconStroke,
  connectorColor: businessFlowPalette.connector,
  connectorOpacity: 0.8,
  connectorStroke: 'dashed',
  connectorWidth: 1,
  gridColor: businessFlowPalette.grid,
  gridDensity: 30,
  gridOpacity: 0,
  iconSize: 44,
  loadStrategy: 'near-viewport',
  maxConcurrentBeams: 6,
  nodeProgressMaxDelay: 1800,
  nodeProgressMinDelay: 500,
  nodeProgressMode: 'outline',
  nodeProgressSize: 15,
  numberOfAuxiliaryConnections: 12,
  resolutionScale: 'display',
  showAuxiliaryNodes: false,
  size: 'min(22rem, 100%)',
  strokeWidth: 0.5,
} satisfies BusinessCoreNodeFlowProps;

export const businessCoreNodeFlowFoundationProps = businessCoreNodeFlowContactProps;
